name: NickUI
api: [3.0.0, 4.0.0]
version: 1.0.0
main: nick\Main
author: DanuRoYT
commands:
 nick:
  description: "Change your nickname by using UI"
  permission: mediflexdev.nick.cmd
  default: op
permissions:
 mediflexdev.nick.cmd:
  description: "The base permission for /nick command"
  default: false
